version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: rp_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-reservation_parking}
      - TZ=${TZ:-Asia/Taipei}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rp_backend
    environment:
      - DATABASE_URL=mysql+pymysql://root:${DB_ROOT_PASSWORD:-password}@db:3306/${MYSQL_DATABASE:-reservation_parking}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:5173}
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - TZ=${TZ:-Asia/Taipei}
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: rp_frontend
    environment:
      - VITE_API_BASE=${VITE_API_BASE:-http://localhost:8000}
      - TZ=${TZ:-Asia/Taipei}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    depends_on:
      backend:
        condition: service_started

volumes:
  db_data:
